export const countrys = [
    {
        id: '1',
        countryName: 'United States',
        formalName: 'United States of America',
        isoAlpha3Code: 'USA',
        isoNumericCode: '840',
        countryTypeID: '1',
        latestRecordedPopulation: '331002651',
        continent: 'North America',
        region: 'Americas',
        subregion: 'Northern America',
        border: 'Canada, Mexico',
        lastEditedBy: 'admin',
        lastEditedOn: 'January 1, 2020',
        validFrom: '2020-01-01',
        validTo: null
    },
    {
        id: '2',
        countryName: 'Canada',
        formalName: 'Canada',
        isoAlpha3Code: 'CAN',
        isoNumericCode: '124',
        countryTypeID: '1',
        latestRecordedPopulation: '37742154',
        continent: 'North America',
        region: 'Americas',
        subregion: 'Northern America',
        border: 'United States',
        lastEditedBy: 'admin',
        lastEditedOn: 'January 1, 2020',
        validFrom: '2020-01-01',
        validTo: null
    },
    {
        id: '3',
        countryName: 'Germany',
        formalName: 'Federal Republic of Germany',
        isoAlpha3Code: 'DEU',
        isoNumericCode: '276',
        countryTypeID: '1',
        latestRecordedPopulation: '83166711',
        continent: 'Europe',
        region: 'Europe',
        subregion: 'Western Europe',
        border: 'Austria, France, Poland',
        lastEditedBy: 'admin',
        lastEditedOn: 'January 1, 2020',
        validFrom: '2020-01-01',
        validTo: null
    },
    {
        id: '4',
        countryName: 'India',
        formalName: 'Republic of India',
        isoAlpha3Code: 'IND',
        isoNumericCode: '356',
        countryTypeID: '2',
        latestRecordedPopulation: '1380004385',
        continent: 'Asia',
        region: 'Asia',
        subregion: 'Southern Asia',
        border: 'Pakistan, China, Nepal',
        lastEditedBy: 'admin',
        lastEditedOn: 'January 1, 2020',
        validFrom: '2020-01-01',
        validTo: null
    },
    {
        id: '5',
        countryName: 'Australia',
        formalName: 'Commonwealth of Australia',
        isoAlpha3Code: 'AUS',
        isoNumericCode: '036',
        countryTypeID: '1',
        latestRecordedPopulation: '25687041',
        continent: 'Oceania',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        border: '',
        lastEditedBy: 'admin',
        lastEditedOn: 'January 1, 2020',
        validFrom: '2020-01-01',
        validTo: null
    }
];