export const people = [
    {
        id: '1',
        fullName: 'John Doe',
        preferredName: 'John',
        searchName: 'John Doe',
        isPermittedToLogon: true,
        logonName: 'john.doe',
        isExternalLogonProvider: false,
        hashedPassword: 'hashedPassword123',
        isSystemUser: true,
        isEmployee: true,
        isSalesPerson: false,
        userPreferences: '{"theme": "dark", "language": "en"}',
        contactId: '1',
        photo: 'https://www.example.com/photos/johndoe.jpg',
        customFields: '{"customField1": "value1", "customField2": "value2"}',
        languageId: '1',
        lastEditedBy: 'admin_user',
        validFrom: '2023-01-01T00:00:00Z',
        validTo: '2024-01-01T00:00:00Z',
    },
    {
        id: '2',
        fullName: 'Jane Smith',
        preferredName: 'Jane',
        searchName: 'Jane Smith',
        isPermittedToLogon: true,
        logonName: 'jane.smith',
        isExternalLogonProvider: true,
        hashedPassword: 'hashedPassword456',
        isSystemUser: false,
        isEmployee: true,
        isSalesPerson: true,
        userPreferences: '{"theme": "light", "language": "fr"}',
        contactId: '2',
        photo: 'https://www.example.com/photos/janesmith.jpg',
        customFields: '{"customField1": "valueA", "customField2": "valueB"}',
        languageId: '2',
        lastEditedBy: 'system_user',
        validFrom: '2023-05-01T00:00:00Z',
        validTo: '2024-05-01T00:00:00Z',
    },
    {
        id: '3',
        fullName: 'Michael Johnson',
        preferredName: 'Mike',
        searchName: 'Michael Johnson',
        isPermittedToLogon: false,
        logonName: 'michael.johnson',
        isExternalLogonProvider: false,
        hashedPassword: 'hashedPassword789',
        isSystemUser: true,
        isEmployee: false,
        isSalesPerson: false,
        userPreferences: '{"theme": "dark", "language": "es"}',
        contactId: '3',
        photo: 'https://www.example.com/photos/michaeljohnson.jpg',
        customFields: '{"customField1": "valueX", "customField2": "valueY"}',
        languageId: '3',
        lastEditedBy: 'admin_user',
        validFrom: '2023-03-01T00:00:00Z',
        validTo: '2024-03-01T00:00:00Z',
    },
    {
        id: '4',
        fullName: 'Emily Davis',
        preferredName: 'Emily',
        searchName: 'Emily Davis',
        isPermittedToLogon: true,
        logonName: 'emily.davis',
        isExternalLogonProvider: true,
        hashedPassword: 'hashedPassword012',
        isSystemUser: false,
        isEmployee: true,
        isSalesPerson: true,
        userPreferences: '{"theme": "light", "language": "de"}',
        contactId: '4',
        photo: 'https://www.example.com/photos/emilydavis.jpg',
        customFields: '{"customField1": "valueP", "customField2": "valueQ"}',
        languageId: '4',
        lastEditedBy: 'system_user',
        validFrom: '2023-07-01T00:00:00Z',
        validTo: '2024-07-01T00:00:00Z',
    },
    {
        id: '5',
        fullName: 'Sarah Wilson',
        preferredName: 'Sarah',
        searchName: 'Sarah Wilson',
        isPermittedToLogon: false,
        logonName: 'sarah.wilson',
        isExternalLogonProvider: false,
        hashedPassword: 'hashedPassword345',
        isSystemUser: true,
        isEmployee: false,
        isSalesPerson: false,
        userPreferences: '{"theme": "dark", "language": "it"}',
        contactId: '5',
        photo: 'https://www.example.com/photos/sarahwilson.jpg',
        customFields: '{"customField1": "valueM", "customField2": "valueN"}',
        languageId: '5',
        lastEditedBy: 'admin_user',
        validFrom: '2023-09-01T00:00:00Z',
        validTo: '2024-09-01T00:00:00Z',
    },
];
